# Generated by Django 4.1.4 on 2023-01-02 15:41

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=255)),
                ('cliente_ruc', models.CharField(blank=True, max_length=200, null=True)),
                ('cli_fecregistro', models.DateTimeField(auto_now=True)),
                ('cli_fecmodificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_archivo', models.FileField(blank=True, null=True, upload_to='archivos/')),
                ('documento_fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informe_mes', models.CharField(max_length=20)),
                ('informe_sostenimiento', models.TextField(max_length=150)),
                ('doc_informe', models.FileField(blank=True, null=True, upload_to='informes/')),
            ],
        ),
        migrations.CreateModel(
            name='Seguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_productos', models.FileField(blank=True, null=True, upload_to='productos/')),
                ('doc_pets', models.FileField(blank=True, null=True, upload_to='pets/')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio_nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tramite_fecha', models.DateField()),
                ('tramite_contacto', models.CharField(max_length=50)),
                ('tramite_nivel_1', models.BooleanField(default=False)),
                ('tramite_nivel_2', models.BooleanField(default=False)),
                ('tramite_nivel_3', models.BooleanField(default=False)),
                ('tramite_nivel_4', models.BooleanField(default=False)),
                ('tramite_descripcion', models.CharField(max_length=200)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramite_cliente', to='cifumiga.cliente')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_tramite', to='cifumiga.tipo_servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio_desc', models.TextField(max_length=150)),
                ('servicio_area', models.CharField(max_length=50)),
                ('servicio_dim', models.CharField(max_length=20)),
                ('servicio_frec', models.CharField(max_length=100)),
                ('servicio_precio', models.CharField(max_length=20)),
                ('doc_contrato', models.FileField(blank=True, null=True, upload_to='contratos/')),
                ('doc_proforma', models.FileField(blank=True, null=True, upload_to='proformas/')),
                ('doc_ficha', models.FileField(blank=True, null=True, upload_to='fichas/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='cifumiga.cliente')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_servicio', to='cifumiga.tipo_servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Seguridad_Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_iperc', models.FileField(blank=True, null=True, upload_to='ipercs/')),
                ('doc_ats', models.FileField(blank=True, null=True, upload_to='atss/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguridad_cliente', to='cifumiga.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacion_contacto', models.CharField(max_length=50)),
                ('operacion_correo', models.CharField(max_length=200)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operacion_cliente', to='cifumiga.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura_contacto', models.CharField(max_length=50)),
                ('factura_correo', models.CharField(blank=True, max_length=200, null=True)),
                ('factura_costo', models.CharField(max_length=20)),
                ('doc_factura', models.FileField(blank=True, null=True, upload_to='facturas/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factura_cliente', to='cifumiga.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Documento_Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documento_cliente', to='cifumiga.cliente')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documento', to='cifumiga.documento')),
            ],
        ),
        migrations.AddField(
            model_name='documento',
            name='documento_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_documento', to='cifumiga.tipo_documento'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=200)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentario_cliente', to='cifumiga.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('doc_certificado', models.FileField(blank=True, null=True, upload_to='certificados/')),
                ('cert_feccreacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificado_cliente', to='cifumiga.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=9)),
                ('emp_feccreacion', models.DateTimeField(auto_now_add=True)),
                ('emp_modificacion', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
